name: Trying a thing :D
on: pull_request

jobs:
  hi:
    name: Sup
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh issue --repo bplaxco/workflow-test \
            create --title "Issue title" --body "No issues. Never submit issues!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Say hello
        id: say-hello
        uses: ./.github/actions/hello-world
