name: Trying a thing :D
on: pull_request

jobs:
  hi:
    name: Sup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Say hello
        id: say-hello
        uses: ./.github/actions/hello-world
