name: Trying a thing :D
on: pull_request_target

jobs:
  hi:
    name: Sup
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        id: say-hello
        uses: ./.github/actions/hello-world
